name: Generate Banner Image

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *" # Runs at midnight UTC every day
  workflow_dispatch:

jobs:
  generate-banner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        continue-on-error: false

      - name: Run today.py to generate banner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python today.py
        continue-on-error: false

      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions-bot@Mad-Chemist.github.io"
          git config --global user.name "Mad-Chemist/GitHub-Actions-Bot"
          git add light_mode.svg dark_mode.svg
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update banner image"
            git push
          fi
